### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by iProgYou** [terryt925/Dragon_Roll#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- It seems to me that genre would be a many-to-many relationship. If you you would need a join table to join a genre and a show.
- In Genres, it says 'show_id references Users' I think that is just a mistake. If you end up doing a joins table though then you can just delete that line entirely.

**Comment by terryt925** [comment]
I added a 'list' array for the user and a 'genres' array for the shows. I do not know if this would work, but it would reflect what is going on in my sample state. When you get a chance, could you look over the changes.

**Comment by terryt925** [comment]
Remove array data types

**Comment by terryt925** [comment]
Just made the changes from List to Bookmarks and removed the arrays from the schema.
