### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by iProgYou** [terryt925/Dragon_Roll#5]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
- So we talked about having a show genres joins table. That table doesn't need to be in your state though. Instead what you would have is an array of genre ids in each show. No need for the show genres slice. Can chat about it further if youd like

**Comment by iProgYou** [comment]
Looks good!

**Comment by terryt925** [comment]
I have added an array for the users slice called 'list', containing the show ids of all of the shows on their show list.

I have done the same with shows calling the array 'genres'. This was done so a show will have a list of genre ids that correspond to the type of genre the show falls under. 

Please let me know if a revision is needed.

**Comment by iProgYou** [comment]
I am not seeing a `genreIds` array in shows for some reason. Did you save your changes?

**Comment by terryt925** [comment]
Just added them.
