### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by iProgYou** [terryt925/Dragon_Roll#6]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
- `GET /api/genres` may be unnecessary. When would you use this route?

**Comment by terryt925** [comment]
I was thinking the `GET /api/genres` may be necessary when a user may want to see a list of genres and find shows that fall under the selected genre. I assumed having a route show the genres index may be helpful.

**Comment by iProgYou** [comment]
Great explanation!

**Comment by iProgYou** [comment]
Make sure to put a colon before each wildcard

**Comment by terryt925** [comment]
Added the changes.
