### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by iProgYou** [terryt925/Dragon_Roll#7]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by iProgYou** [comment]
- Errors look a bit strange when they line wrap. Maybe smaller errors, but also take out the line wrap. You may need to make its html container bigger
- Make `log in now` and `Join us today` a slightly different color so it is more obvious they are links
- Does it intentionally redirect to login if your aren't signed in? When typing a random route it takes me to the splash it looks like

**Comment by terryt925** [comment]
I have completed the fixes to my user auth. Please let me know if there is anything you would like me to fix. Thank you!
